---
title: Can't Stop Columbus
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  author:
    title: author
    output: true
defaults:
- scope:
    path: ''
    type: pr
  values:
    permalink: "/pr/:title/"
    layout: pr
url: https://www.cantstopcolumbus.com
baseurl: 
tagline: We're all in this together.
plugins:
- jekyll-autoprefixer
- jekyll-seo-tag
- jekyll-sitemap
email: hello@cantstopcolumbus.com
description: On Sunday, March 15, 2020, the Columbus, Ohio tech and business community
  started talking about the idea of a virtual hackathon in response to the Covid-19
  situation. With social distancing, no school, remote work, and a sense of urgency,
  there's a lot of energy focused on helping. We proposed an online hacking event
  where anyone can  contribute by defining challenges, building projects, and sharing
  resources.
author: Can't Stop Columbus
google_analytics: UA-111111111-1
twitter:
  username: cantstopcbus
  card: summary
exclude:
- README.md
- Gemfile.lock
- Gemfile
