name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Jekyll Builder for GitHub Pages
      uses: meitar/jekyll-builder-for-github-pages-action@v1

    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: 205.186.128.139
        user: developer@cantstopcolumbus.com
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "_site"
        remoteDir: "/"
