name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

    # - name: FTP Deploy
    #   uses: SamKirkland/FTP-Deploy-Action@3.0.0
    #   with:
    #     ftp-server: 205.186.128.139
    #     ftp-username: developer@cantstopcolumbus.com
    #     ftp-password: ${{ secrets.FTP_PASSWORD }}
    #     local-dir: ./_site
    #     remote-root:  /
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: 205.186.128.139
        user: developer@cantstopcolumbus.com
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "_site"
        remoteDir: "/"
